version: '3'

services:
    backend:
        build: .
        image: dbl:latest
        entrypoint: /bin/sh ./entrypoint.sh
        command: python manage.py runserver 0.0.0.0:8080
        volumes:
            - .:/app
        ports:
            - 80:8080
        depends_on:
            - db
        env_file:
            - ./.env

    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        networks:
            - default
        depends_on:
            - db
        env_file:
            - .env
        ports:
            - 5050:5050

volumes:
    postgres_data:
