# Generated by Django 3.2.15 on 2022-08-26 20:07

import dblapp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryRecord',
            fields=[
                ('factory_id', models.CharField(default=dblapp.models.random_string_1, editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('org_id', models.CharField(default=dblapp.models.random_string_2, max_length=4)),
                ('country', models.CharField(blank=True, choices=[('VN', 'Vietnam'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('SG', 'Singapore'), ('TH', 'Thailand')], default='VN', max_length=10)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('fail_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('defect_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
    ]
