name: test/build backend

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.7"
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --max-line-length 79 ./ -q --exclude ./dbl/settings.py --count --statistics
    - name: Security with Bandit
      run: |
        pip install bandit
        bandit ./ -r -n 1 --skip B311,B104
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: generate opply-app .env
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        envkey_DJANGO_DEBUG: ${{ secrets.DJANGO_DEBUG }}
        envkey_POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
        envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        envkey_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        envkey_DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
        envkey_DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        envkey_DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        envkey_PGADMIN_LISTEN_PORT: ${{ secrets.PGADMIN_LISTEN_PORT }}
        envkey_PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
        envkey_PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
        file_name: .env
        fail_on_empty: true
    - name: Spin up docker-compose
      run: |
        docker-compose build && docker-compose up -d
    - name: coverage setting
      run: |
        docker-compose exec -T backend /bin/sh -c "coverage run manage.py test >/dev/null 2>&1"
      continue-on-error: true
    - name: coverage report
      run: |
        docker-compose exec -T backend /bin/sh -c "coverage report -m"
